@baseUrl = http://localhost:3000
@token = {{user_login.response.body.access_token}}
@refreshed_token = {{refresh_token.response.body.access_token}}
@userId = {{user_login.response.body.user.id}}

@postId = {{list_posts.response.body.$[0].id}}

### List Users
GET {{baseUrl}}/user?page=1&limit=10
Authorization: Bearer {{token}}

### Find User

GET {{baseUrl}}/user/{{userId}}
Authorization: Bearer {{token}}

### Create New User

POST {{baseUrl}}/user/ 
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "John 2",
    "email": "richard2.teste@gmail.com",
    "password": "password"
} 

### Update User

PUT  {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "8f56ce28-72d1-489c-8956-660d97830441",
    "name": "John",
    "email": "richard.esclima@gmail.com",
    "password": "password"
} 

### Delete User
Authorization: Bearer {{token}}
DELETE {{baseUrl}}/user/cb76f931-a491-4631-a871-888fa94aa330


### User login 
# @name user_login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "richard1.teste@gmail.com",
    "password": "password"
}

### Refresh Token
# @name refresh_token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refresh_token": "{{user_login.response.body.refresh_token}}"
}

### Create a Post

POST {{baseUrl}}/post
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Post 2",
    "content": "Content 2"
}

### Update a Post
PUT {{baseUrl}}/post
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "687f7388-1063-4543-bdbf-9cd26b33eb2c",
    "title": "Post 2",
    "content": "Content 1"
}

### List Posts 
# @name list_posts

GET {{baseUrl}}/post?page=1&limit=2
Authorization: Bearer {{token}}

### Find Post
GET {{baseUrl}}/post/687f7388-1063-4543-bdbf-9cd26b33eb2c
Authorization: Bearer {{token}}

### Delete Post
DELETE {{baseUrl}}/post/687f7388-1063-4543-bdbf-9cd26b33eb2c
Authorization: Bearer {{token}}

### Find User Posts
GET {{baseUrl}}/post/user/{{userId}}?page=1&limit=1
Authorization: Bearer {{token}}

### Find Current User Posts
GET {{baseUrl}}/post/my-posts?page=1&limit=2
Authorization: Bearer {{token}}

### React To Post
POST {{baseUrl}}/post/react/{{postId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "type": "unlike"
}
