@baseUrl = http://localhost:3000

### List Users
GET {{baseUrl}}/user?page=1&limit=10

### Find User

GET {{baseUrl}}/user/1

### Create New User

POST {{baseUrl}}/user/ 
Content-Type: application/json

{
    "name": "John",
    "email": "richard.teste@gmail.com",
    "password": "password"
} 

### Update User

PUT  {{baseUrl}}/user
Content-Type: application/json

{
    "id": "cb76f931-a491-4631-a871-888fa94aa330",
    "name": "John",
    "email": "richard.esclima@gmail.com",
    "password": "password"
} 

### Delete User

DELETE {{baseUrl}}/user/cb76f931-a491-4631-a871-888fa94aa330


### User login 
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "richard.esclima@gmail.com",
    "password": "password"
}